base:
	@scripts/base.sh

destroy:
	@scripts/destroy.sh

push:
	@git add .
	@git commit -m "autogenerated"
	@git push origin main

# init:
# 	@cd terraform/ && terraform init

# plan:
# 	@cd terraform/ && terraform plan -var "service=${service}" -var "project=${project}" -var "env=${env}" -var "domain=${domain}"

# apply:
# 	@cd terraform/ && terraform apply -var "service=${service}" -var "project=${project}" -var "env=${env}" -var "domain=${domain}"

# destroy:
# 	@cd terraform/ && terraform destroy -var "service=${service}" -var "project=${project}" -var "env=${env}" -var "domain=${domain}"